#!/usr/bin/env python3
"""Reference values of analytical_seepage.py for the C++ port (AnalyticalSeepage.h of the NeoPZ project).

For a fixed list of cases (beta, alpha, h_w/H, H, gamma_w; L_m = 10 H) the script writes the scalars of the optimum
and the seepage force f = K^-1 . v'_opt at random points, in paper coordinates (x right, y DOWN), as read by
`SlopeSeepageForces analytical ref=<file>` and by `SlopeSeepageForces check`:

    C,<case>,<beta_deg>,<alpha>,<H>,<hw>,<gamma_w>,<Lm_over_H>,<degenerate>,<m>,<C/h2e^2>,<D/h2e^2>,<F>,<J*/(k_h H^2 gw^2)>
    P,<case>,<x>,<y>,<fx>,<fy>

Points of each case (a third of them outside the soil, where f = 0 is expected):
    40 %  log-polar around the crest edge O: r log-uniform in [1e-4 H, 1.3 R_e], theta uniform in [0, pi]
    40 %  uniform in the box x in [-3 H, x_T + 3 H], y in [-0.25 H, 3 H]
    20 %  close to the circles r = R_w, R, R_e (relative distance 1e-8 .. 1e-2 on either side)

usage:
    python3 analytical_seepage_reference.py                       # 300 points per case -> data/analytical_seepage_reference.csv
    python3 analytical_seepage_reference.py --npts 100000 --out <file>   # full comparison (93 MB, not stored)
"""
from __future__ import annotations

import argparse
import os
import sys
import time

import numpy as np

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)
from analytical_seepage import AnalyticalSeepage  # noqa: E402

DATA_DIR = os.path.join(os.path.dirname(SCRIPT_DIR), "data")

# beta (deg), alpha, h_w / H, H (m), gamma_w (kN/m^3): steep (degenerate m -> 0) and flat slopes, the near-threshold
# cases beta = 80 / alpha = 1 (m = 0.037) and beta = 88 / alpha = 4 (m = 0.014), and h_w = 0 (f = 0)
CASES = [
    (15, 1, 1.0, 1.0, 9.81),
    (30, 5, 0.5, 5.0, 9.81),
    (45, 10, 0.05, 5.0, 9.81),
    (60, 1, 0.05, 1.0, 9.8),
    (75, 5, 1.0, 10.0, 9.81),
    (80, 1, 1.0, 1.0, 9.81),
    (85, 1, 1.0, 5.0, 9.81),
    (90, 1, 0.5, 5.0, 9.8),
    (90, 10, 1.0, 5.0, 9.81),
    (20, 10, 0.5, 1.0, 9.81),
    (83, 2, 0.05, 1.0, 9.81),
    (88, 4, 0.5, 5.0, 9.81),
    (45, 2, 0.0, 5.0, 9.81),
]
LM_OVER_H = 10.0


def sample_points(md, n, rng):
    H = md.H
    n1, n2 = int(0.4 * n), int(0.4 * n)
    n3 = n - n1 - n2
    r = np.exp(rng.uniform(np.log(1e-4 * H), np.log(1.3 * md.Re), n1))
    th = rng.uniform(0.0, np.pi, n1)
    x1, y1 = -r * np.cos(th), r * np.sin(th)
    x2 = rng.uniform(-3.0 * H, md.xtoe + 3.0 * H, n2)
    y2 = rng.uniform(-0.25 * H, 3.0 * H, n2)
    radii = np.array([md.Rw if md.Rw > 0 else md.R, md.R, md.Re])
    rk = radii[rng.integers(0, 3, n3)]
    delta = rng.choice([-1.0, 1.0], n3) * 10.0 ** rng.uniform(-8.0, -2.0, n3)
    r3 = rk * (1.0 + delta)
    th3 = rng.uniform(0.0, np.pi, n3)
    x3, y3 = -r3 * np.cos(th3), r3 * np.sin(th3)
    return np.concatenate([x1, x2, x3]), np.concatenate([y1, y2, y3])


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--npts", type=int, default=300, help="points per case (default 300)")
    ap.add_argument("--out", default=os.path.join(DATA_DIR, "analytical_seepage_reference.csv"))
    ap.add_argument("--seed", type=int, default=20251)
    args = ap.parse_args()
    t0 = time.time()
    with open(args.out, "w") as out:
        out.write("# reference of scripts/analytical_seepage.py for AnalyticalSeepage.h (generated by "
                  "scripts/analytical_seepage_reference.py --npts %d --seed %d)\n" % (args.npts, args.seed))
        out.write("# C,case,beta_deg,alpha,H,hw,gamma_w,Lm_over_H,degenerate,m,C/h2e^2,D/h2e^2,F,Jstar/(kh H^2 gw^2)\n")
        out.write("# P,case,x,y,fx,fy   (paper coordinates: x right, y down; f = K^-1 v'_opt in kN/m^3)\n")
        for ic, (beta, alpha, hwr, H, gw) in enumerate(CASES):
            md = AnalyticalSeepage(beta, H, hwr * H, alpha, gamma_w=gw, Lm_over_H=LM_OVER_H)
            h2e2 = md.h2e ** 2
            out.write("C,%d,%r,%r,%r,%r,%r,%r,%d,%.17g,%.17g,%.17g,%.17g,%.17g\n"
                      % (ic, float(beta), float(alpha), H, md.hw, gw, LM_OVER_H, int(md.degenerate), md.m,
                         md.C / h2e2, md.D / h2e2, md.F, md.Jstar_normalized()))
            rng = np.random.default_rng(args.seed + ic)
            x, y = sample_points(md, args.npts, rng)
            fx, fy = md.force(x, y)
            for row in zip(x, y, fx, fy):
                out.write("P,%d,%.17g,%.17g,%.17g,%.17g\n" % ((ic,) + row))
            print(f"case {ic}: {md.summary()}", flush=True)
    print(f"written {args.out} ({os.path.getsize(args.out) / 1e6:.1f} MB, {time.time() - t0:.1f} s)")


if __name__ == "__main__":
    main()
